### ISSUE TITLE
hmmpress command is not running in rabifier

### ISSUE THREAD

**Issue by HeenaBioinfo** [evocell/rabifier#1]
Hi I have built the dir superfamily,

but when I run hmmpress, it is not running:

$ hmmpress hmmlib_1.75
Working...    SSI index construction failed:
  secondary keys not unique: '100879' occurs more than once

Please reply.

Thanks

Heena

**Comment by jsurkont** [comment]
Hi. I has been a few year since I last worked on the project. That being said, I've just run a quick test and I can't reproduce the issue, see below.

```bash
$ mkdir superfamily
$ cd superfamily
$ wget --http-user USERNAME --http-password PASSWORD -r -np -nd -e robots=off \
           -R 'index.html*' 'http://supfam.org/SUPERFAMILY/downloads/license/supfam-local-1.75/'
$ gzip -d *.gz
$ hmmpress hmmlib_1.75 
Working...    done.
Pressed and indexed 15438 HMMs (15438 names and 15438 accessions).
Models pressed into binary file:   hmmlib_1.75.h3m
SSI index for binary model file:   hmmlib_1.75.h3i
Profiles (MSV part) pressed into:  hmmlib_1.75.h3f
Profiles (remainder) pressed into: hmmlib_1.75.h3p
$ hmmpress -h
# hmmpress :: prepare an HMM database for faster hmmscan searches
# HMMER 3.1b1 (May 2013); http://hmmer.org/
# Copyright (C) 2013 Howard Hughes Medical Institute.
# Freely distributed under the GNU General Public License (GPLv3).
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Usage: hmmpress [-options] <hmmfile>

Options:
  -h : show brief help on version and usage
  -f : force: overwrite any previous pressed files
```

**Comment by HeenaBioinfo** [comment]
Hi Thanks for your reply,
I am able to solve the problem, now hmmpress is running
I think the issue was system compatibility, 
I have also installed all the dependencies now, but I get a new error while running rabifier:

(base) Tower-Workstation:/space/superfamily$ rabifier sequences.fa
Traceback (most recent call last):
  File "/home/heena/miniconda3/bin/rabifier", line 5, in <module>
    rabifier.rabmyfire.main()
  File "/home/heena/miniconda3/lib/python3.7/site-packages/rabifier/rabmyfire.py", line 556, in main
    subfamily_score=args.subfamily_score
  File "/home/heena/miniconda3/lib/python3.7/site-packages/rabifier/rabmyfire.py", line 472, in __init__
    self.check()
  File "/home/heena/miniconda3/lib/python3.7/site-packages/rabifier/rabmyfire.py", line 481, in check
    if pathfinder.add_path(pathfinder['superfamily']) is None:
  File "/home/heena/miniconda3/lib/python3.7/site-packages/rabifier/utils.py", line 52, in add_path
    if os.path.exists(path):
  File "/home/heena/miniconda3/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
**TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType**


(base) Tower-Workstation:/space/superfamily$ ls
 a2m2selex.pl       download.html      hmmlib_1.75.h3m  'index.html?C=D;O=A'    'index.html?C=M;O=A.1'  'index.html?C=N;O=D'    'index.html?C=S;O=D.1'   pdbj95d         superfamily.pl
 ass3.pl            fasta_checker.pl   hmmlib_1.75.h3p  'index.html?C=D;O=A.1'  'index.html?C=M;O=D'    'index.html?C=N;O=D.1'   LICENSE                 rabifier-data   tmpdirprankmsarLBlc2
 ass_to_html.pl     hmmlib_1.75        hmmscan.pl       'index.html?C=D;O=D'    'index.html?C=M;O=D.1'  'index.html?C=S;O=A'     meme-5.1.1              README
 dir.cla.scop.txt   hmmlib_1.75.h3f    index.html       'index.html?C=D;O=D.1'  'index.html?C=N;O=A'    'index.html?C=S;O=A.1'   meme-5.1.1.tar.gz       self_hits.tab
 dir.des.scop.txt   hmmlib_1.75.h3i    index.html.1     'index.html?C=M;O=A'    'index.html?C=N;O=A.1'  'index.html?C=S;O=D'     model.tab               sequences.fa

(base)Tower-Workstation:/space/superfamily$ head sequences.fa 
>rab8
MAASGGKTYDYLFKLLLIGDSGVGKTCVLFRFSEDHFNSTFISTIGIDFKIRTIDLDGKKVKLQIWDTAGQERFRTITTA
YYRGAMGIMLVYDITNDKSFENIKNWIRNIEEHASSDVKR
>rab11
MPQEEEAEYLFKIVIIGDSAVGKSNLLNRFTRNEFTEKTKATIGVDFGTKSIEIDNKTITAQCWDTAGQERFRAVTSGYY
RGAVGAMIVYDITSKISFKNVTRWLNELREMAEQDILIMMVGNKSDLEMSREVPTKEAQAFAESNKISFLETSALNSTNV
NQSFERLLTDIYHLVSSKKPMVVDDTQNWLVPNQGKKLTPLSDPAPQLTANTTSTHQEKKSGCC
>myoglobin
MGLSDGEWQLVLNVWGKVEADIPGHGQEVLIRLFKGHPETLEKFDKFKHLKSEDEMKASEDLKKHGATVLTALGGILKKK
GHHEAEIKPLAQSHATKHKIPVKYLEFISECIIQVLQSKHPGDFGADAQGAMNKALELFRKDMASNYKELGFQG

To confirm that rabifier is installed correctly:

(base) heena@heena-HP-Z240-Tower-Workstation:/space/Kunal/superfamily$ rabifier
usage: rabifier [-h] [-v] [-o OUTPUT] [--outfmt {text,json,csv}]
                [--show_positive] [--cpu CPU] [--fast] [--bh_evalue BH_EVALUE]
                [--motif_evalue MOTIF_EVALUE] [--motif_number MOTIF_NUMBER]
                [--subfamily_identity SUBFAMILY_IDENTITY]
                [--subfamily_score SUBFAMILY_SCORE]
                input
rabifier: error: the following arguments are required: input

I have also tried **rabifier "sequences.fa"** - but got same error

I have also tried searching this error online, but could not get an answer.

Do you have any idea if this is a problem with being python is not in the $PATH?

Thanks

Heena.

**Comment by HeenaBioinfo** [comment]
Hi Sorry for bothering, I am getting this new error now:

(base) Tower-Workstation:/space/superfamily$ rabifier sequences.fa
usage: rabifier [-h] [-v] [-o OUTPUT] [--outfmt {text,json,csv}]
                [--show_positive] [--cpu CPU] [--fast] [--bh_evalue BH_EVALUE]
                [--motif_evalue MOTIF_EVALUE] [--motif_number MOTIF_NUMBER]
                [--subfamily_identity SUBFAMILY_IDENTITY]
                [--subfamily_score SUBFAMILY_SCORE]
                input
**rabifier: error: 'superfamily' data directory is missing**

I have installed pathfinder also but still the same error..

I have noticed in python script rabmyfire.py : it says 
 pathfinder = Pathfinder(True)
        if pathfinder.add_path(pathfinder['superfamily']) is None:
            raise RuntimeError("'superfamily' data directory is missing")

**Comment by jsurkont** [comment]
Hi, sorry for the late reply.
It looks that you don't have the `superfamily` folder in your path. Running rabifier in the superfamily folder will not work.
You can add it by updating your `PATH` environmental variable `export PATH="$PATH:/path/to/the/superfamily/folder"`
